.PHONY: clean All

All:
	@echo "----------Building project:[ Progetto_algoritmi - Debug ]----------"
	@cd "Progetto_algoritmi" && "$(MAKE)" -f  "Progetto_algoritmi.mk"
clean:
	@echo "----------Cleaning project:[ Progetto_algoritmi - Debug ]----------"
	@cd "Progetto_algoritmi" && "$(MAKE)" -f  "Progetto_algoritmi.mk" clean
