.PHONY: clean All

All:
	@echo "----------Building project:[ Prop_ins_laurea - Debug ]----------"
	@cd "Prop_ins_laurea" && "$(MAKE)" -f  "Prop_ins_laurea.mk"
clean:
	@echo "----------Cleaning project:[ Prop_ins_laurea - Debug ]----------"
	@cd "Prop_ins_laurea" && "$(MAKE)" -f  "Prop_ins_laurea.mk" clean
