.PHONY: clean All

All:
	@echo "----------Building project:[ Implementazione_albero_rb_alternativa - Debug ]----------"
	@cd "Implementazione_albero_rb_alternativa" && "$(MAKE)" -f  "Implementazione_albero_rb_alternativa.mk"
clean:
	@echo "----------Cleaning project:[ Implementazione_albero_rb_alternativa - Debug ]----------"
	@cd "Implementazione_albero_rb_alternativa" && "$(MAKE)" -f  "Implementazione_albero_rb_alternativa.mk" clean
